spring.application.name=ms-users
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/pruebaTecnica?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=${APP_JWT_SECRET:gyGM7Hklb0Uq1scptI1MThupvEbVWJHceadpjbv4W3oZQxmYyfz4ZZUluc0Ef1aKNQFBU7NzmpBiWtlqLXb4VT}
app.jwt.expiration-ms=86400000
app.jwt.issuer=ms-users

logging.level.org.springframework.security=INFO
