spring.application.name=ms-orders
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/pruebaTecnica?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=cambia_este_secreto_super_largo_de_al_menos_32_bytes_0123456789ABC

app.services.products-url=http://localhost:8082
